name: CI - Code Quality & Testing

on: [push, pull_request]

jobs:
  quality-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          uv sync

      - name: Run Linting (Ruff)
        run: uv run ruff check .

      - name: Run Type Checking (Mypy)
        run: uv run mypy .

      - name: Run Security Scan (Bandit)
        run: uv run bandit --exclude "./.venv" -r .

      # - name: Run Tests with Coverage
      #   run: uv run pytest --cov=app
